### ISSUE TITLE
Discontinued products does not redirect

### ISSUE THREAD

**Issue by minosantoro** [adampmoss/CreareSEO#73] opened 2016-07-28 14:26 UTC
Using the redirect function for discontinued products and selecting from the available options, do not get any redirects but only 404.
Have you any suggestions to solve the problem?

Magento 1.9.1.0 Version
Create SEO 1.4.1 Version

**Comment by hejhog** [comment] 2016-08-27 17:00
Same issue but creates a blank page. Not sure if this caused by CreareSEO.
If you disable compilation then the problem disappears. I also disabled the Creare module (xml to false) and I still get a blank page on disabled products with compilation enabled.
Therefore this may be a 1.9.x problem.  However, difficult to debug as, even with error codes enabled, still get a blank page and no error logs.

**Comment by kryss05** [comment] 2016-10-27 15:19
I have same problem in 1.9.4.2, only 404 error. I use 1.4.1 version for CreareSeo.

**Comment by adampmoss** [comment] 2016-10-27 21:06
@hejhog is correct this is a problem with Magento core when used with compilation, I'm not sure if this has been fixed in latest Magento versions.

**Closed by adampmoss** 2016-10-27 21:06 UTC

**Comment by hejhog** [comment] 2017-06-11 05:10
This is an issue with Magento.  The following will resolve the problem.
lib/Varien/Autoload.php

Find static public function registerScope($code).
Change **include** to **include_once**

Upload to local code - app/code/local/Varien/Autoload.php
