### ISSUE TITLE
Should canonicals not be either http or https

### ISSUE THREAD

**Issue by will-b** [adampmoss/CreareSEO#45] opened 2016-01-08 20:45 UTC
In Block/Page/Html/Head/Cmscanonical.php the canonical changes to http and https. Should it be one or the other and not switch depending on the scheme?

**Comment by adampmoss** [comment] 2016-10-27 20:46
Duplicate of #72 - will be fixed in upcoming release

**Closed by adampmoss** 2016-10-27 20:46 UTC
