### ISSUE TITLE
Fatal Error when Make "alt" tags madatory is enabled

### ISSUE THREAD

**Issue by hejhog** [adampmoss/CreareSEO#134] opened 2017-10-10 22:41 UTC
Set Make "alt" tags mandatory on product gallery images? => Yes

Try to edit a product.

Fatal error: Undefined class constant 'XML_NODE_PRODUCT_MAX_DIMENSION' in /app/design/adminhtml/default/default/template/creareseo/catalog/product/helper/gallery.phtml on line 85

**Comment by sprankhub** [comment] 2017-10-15 14:33
Duplicate of https://github.com/adampmoss/CreareSEO/issues/93

**Closed by sprankhub** 2017-10-15 14:33 UTC
