### ISSUE TITLE
Parsing error: Missing '}' or object member name

### ISSUE THREAD

**Issue by simoncrewe** [adampmoss/CreareSEO#154] opened 2019-05-20 11:45 UTC
Hi,
I've added latest version but it's still the same.
Error seems to be the comma at the end of "name".
"name": "Front 2 Single Ford Transit Courier Fully Tailored",
If comma is deleted, the json schema shows no errors.

Please advise

Cheers,

Simon

**Comment by sprankhub** [comment] 2019-05-20 12:45
Duplicate of #153.

**Closed as completed by sprankhub** 2019-05-20 12:45 UTC
